version: "3"
services:
  notebook:
    # https://hub.docker.com/r/jupyter/datascience-notebookからimageをpullする
    build: .
    # ポートの設定("ホスト：コンテナ")
    ports:
      - "8888:8888"
    # 環境変数の設定
    environment:
      - JUPYTER_ENABLE_LAB=yes
    # ボリューム(データの永続化の場所)の設定(ホスト:コンテナ)
    # ホスト内のworkディレクトリとコンテナ内の/home/jovyan/workディレクトリが紐づいているイメージ
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    command: /usr/local/bin/jupyter lab --ip=0.0.0.0 --port 8888 --allow-root
      --NotebookApp.token=''
